language: cpp
compiler: gcc
sudo: required
dist: bionic
git:
  depth: 3


matrix:
  include:
  - name: "VS 2017 + VS2019"
    os: windows
    before_install:
      - powershell.exe -ExecutionPolicy Bypass -NoProfile -NonInteractive -File windows_setup.ps1
    install:
      - choco install visualstudio2019community
      - choco install python3 -y --override --installarguments "'/quiet  InstallAllUsers=1 TargetDir=c:\\Python'"
      - export PATH="/c/Python/Scripts:$PATH"
      - pip3 install conan
    script:
      - conan --version
