language: cpp
compiler: gcc
sudo: required
dist: bionic
git:
  depth: 3


matrix:
  include:
  - name: "VS 2017 + VS2019"
    os: windows
    before_install:
      - powershell.exe -ExecutionPolicy Bypass -NoProfile -NonInteractive -File windows_setup.ps1
    install:
      - choco install visualstudio2019community
      - choco install python3 -y --override --installarguments "'/quiet  InstallAllUsers=1 TargetDir=c:\\Python'"
      - export PATH="/c/Python:/c/Python/Scripts:$PATH"
      - python -V
      - pip3 install conan
      - conan user
      - mkdir -p .conan/profiles
      - cp default VS2017 .conan/profiles
      - export CONAN_PRINT_RUN_COMMANDS=1
    script:
      - cd vorb_test/all
      - python build-libvorbis-conan.py --configure --profile default
      - python build-libvorbis-conan.py --configure --profile VS2017
