language: shell
git:
  depth: 3


matrix:
  include:
  - name: "VS 2017 + VS2019"
    os: windows
    before_install:
      - powershell.exe -ExecutionPolicy Bypass -NoProfile -NonInteractive -File windows_setup.ps1
    install:
#      - choco install visualstudio2019community --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
      - choco install python3 -y --override --installarguments "'/quiet  InstallAllUsers=1 TargetDir=c:\\Python'"
      - export PATH="/c/Python:/c/Python/Scripts:$PATH"
      - python -V
      - pip3 install conan
      - conan user
      - mkdir -p $HOME/.conan/profiles
      - cp default VS2017 $HOME/.conan/profiles
      - export CONAN_PRINT_RUN_COMMANDS=1
    script:
      - ./build.bat
